### ISSUE TITLE
ts_start and ts_end missed

### ISSUE THREAD

**Issue by DonPipo85** [christophsax/tsbox#138]
Hi there, 
so many of my scripts use ts_end and ts_start, which are deprecated for tsbox 0.1.0. I dont see the improvement of using ts_summary(x)$start and ts_summary(x)$end instead. Any way to get these functions back?

**Comment by christophsax** [comment]
deprecated means they are still working, and I will keep them that way for a while.

`ts_summary(x)$start` is better than `ts_start` because it gives the start-dates of every series. It is also more consistent and works the same way as `ts_summary(x)$freq`, `ts_summary(x)$diff` etc.

**Comment by christophsax** [comment]
I may remove deprecation, and just remove them from documentation?

**Comment by christophsax** [comment]
@DonPipo85: realized that these two functions were not exported incidentally. They are back in latest, with a deprecated warning.

I will leave them deprecated for a long time, so your code will still work.

But the two function really have a bad design, because they return the start and end of the *longest* time series. This is quite arbitrary. The long term plan is to get rid of them.
